TrainingApp/Areas/Admin/Controllers/AppUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TrainingApp.DataAccess.Repository.IRepository;
using TrainingApp.Models;

namespace TrainingApp.Areas.Admin.Controllers
{
    public class AppUserController : Controller
    {
        private IApplicationUserRepo iApplicationUserRepo;
        private UserManager<ApplicationUser> userManager;

        public AppUserController(IApplicationUserRepo applicationUserRepo, UserManager<ApplicationUser> UserManager)
        {
            iApplicationUserRepo = applicationUserRepo;
            userManager = UserManager;
        }

        public string GetCurrentRoles(string Id)
        {
            return iApplicationUserRepo.GetCurrentRoles(Id);
        }

        public string GetAvailableRoles(string Id)
        {
            return iApplicationUserRepo.GetAvailableRoles(Id);
        }

        [HttpGet]
        public IActionResult AssignAppUsers()
        {
            ViewData["AppUsers"] = new SelectList(iApplicationUserRepo.ListAllApplicationUsers(), "Id", "fullName");

            return View();
        }
        [HttpPost]
        public IActionResult AssignAppUsers(string submitButton, string ddlAppUsers, List<string> availableRoles, List<string> currentRoles)

        {
            string userID = ddlAppUsers;
            ApplicationUser user = iApplicationUserRepo.FindUser(userID);


            if (submitButton == "AddRoles")
            {
                userManager.AddToRolesAsync(user, availableRoles).Wait();
            }
            else if (submitButton == "RemoveRoles")
            {
                userManager.RemoveFromRolesAsync(user, currentRoles).Wait();
            }

            ViewData["AppUsers"] = new SelectList(iApplicationUserRepo.ListAllApplicationUsers(), "Id", "fullName", userID);


            return View();
        }
    }
}

TrainingApp/Areas/Trainers/Controllers/TrainerScheduleController.cs
using TrainingApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System.Security.Claims;
using TrainingApp.DataAccess.Repository.IRepository;
using TrainingApp.Models;

namespace TrainingApp.Areas.Trainers.Controllers
{
    public class TrainerScheduleController : Controller
    {
        private ITrainerRepo iTrainerRepo;
        private ITrainerScheduleRepo iTrainerScheduleRepo;
        private IApplicationUserRepo iApplicationUserRepo;
        private ITrainingSessionRepo iTrainingSessionRepo;


        public TrainerScheduleController(ITrainerRepo repo, ITrainerScheduleRepo trainerScheduleRepo, IApplicationUserRepo applicationUserRepo, ITrainingSessionRepo trainingSessionRepo)
        {
            iTrainerRepo = repo;
            iTrainerScheduleRepo = trainerScheduleRepo;
            iApplicationUserRepo = applicationUserRepo;
            iTrainingSessionRepo = trainingSessionRepo;
        }

        public void PopulateDropDownList()
        {
            ViewData["TrainerList"] = new SelectList(iTrainerRepo.ListAllAvailableTrainers(), "trainerId", "UserName");
        }

        [HttpGet]
        public IActionResult SearchTrainers()
        {
            PopulateDropDownList();

            SearchTrainersViewModel trainerViewModel = new SearchTrainersViewModel();

            return View(trainerViewModel);
        }

        [HttpPost]
        public IActionResult SearchTrainers(SearchTrainersViewModel trainerViewModel)
        {
            PopulateDropDownList();

            trainerViewModel.trainerScheduleList = SearchTrainersHelper(trainerViewModel);

            return View(trainerViewModel);
        }

        public List<TrainerSchedule> SearchTrainersHelper(SearchTrainersViewModel trainerViewModel)
        {
            List<TrainerSchedule> trainersSchedulesList = iTrainerScheduleRepo.ListOfTrainerSchedules();

            if (trainerViewModel.SportType != null)
            {
                trainersSchedulesList = trainersSchedulesList.Where(t => t.trainer.sportType == trainerViewModel.SportType).ToList();


            }

            return trainersSchedulesList;

        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AddTrainers()
        {
            PopulateDropDownList();

            return View("~/Views/TrainerSchedule/AddTrainers.cshtml");
        }

        [HttpPost]
        public IActionResult AddTrainers(AddTrainersViewModel trainerViewModel)
        {
            if (ModelState.IsValid)
            {
                //1. Add a Trainer
                Trainer trainer = new Trainer(trainerViewModel.firstName, trainerViewModel.lastName, trainerViewModel.sportType, trainerViewModel.email, trainerViewModel.phoneNumber, trainerViewModel.passWord);
                AddTrainerHelper(trainer).Wait();

                //2. Add Trainer Schedule
                string trainerId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                TrainerSchedule trainerSchedule = new TrainerSchedule(trainerViewModel.StartDateTime, trainerViewModel.EndDateTime, trainerId);
                AddTrainerScheduleHelper(trainerSchedule).Wait();

                return RedirectToAction("SearchTrainers");
            }// end of is valid true
            else
            {
                PopulateDropDownList();
                return View("~/Views/TrainerSchedule/AddTrainers.cshtml"); // returns them back to page if they dont provide the correct infomoration
            }// end of is valid false
        }// end of addtrainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditTrainer(string TrainerID)
        {

            Trainer trainer = iTrainerRepo.FindTrainer(TrainerID);

            return View("~/Views/TrainerSchedule/EditTrainers.cshtml", trainer);
        }//end of edit trainer post method

        [HttpPost]
        public IActionResult EditTrainer(Trainer trainer)
        {

            iTrainerRepo.EditTrainerAsync(trainer).Wait();

            return RedirectToAction("SearchTrainers");

        } //end of edit trainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult ConfirmDeleteTrainers(string TrainerID)
        {

            Trainer trainer = iTrainerRepo.FindTrainer(TrainerID);

            return View("~/Views/TrainerSchedule/ConfirmDeleteTrainers.cshtml", trainer);
        }//end of delete trainer get method

        [HttpPost]
        public IActionResult DeleteTrainer(Trainer trainer)
        {

            iTrainerRepo.DeleteTrainerAsync(trainer).Wait();

            return RedirectToAction("SearchTrainers");
        }//end of delete trainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditTrainerSchedule(int TrainerScheduleID)
        {

            TrainerSchedule trainerSchedule = iTrainerScheduleRepo.FindTrainerSchedule(TrainerScheduleID);

            return View("~/Views/TrainerSchedule/EditTrainerSchedule.cshtml", trainerSchedule);
        } // end of edit trainer schedule get method

        [HttpPost]
        public IActionResult EditTrainerSchedule(TrainerSchedule trainerSchedule)
        {

            iTrainerScheduleRepo.EditTrainerScheduleAsync(trainerSchedule).Wait();

            return RedirectToAction("SearchTrainers");

        } // end of edit trainer schedule post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult ConfirmDeleteTrainersSchedule(int TrainerScheduleID)
        {

            TrainerSchedule trainerSchedule = iTrainerScheduleRepo.FindTrainerSchedule(TrainerScheduleID);

            return View("~/Views/TrainerSchedule/EditTrainerSchedule.cshtml", trainerSchedule);
        }// end of confirm delete trainer schedule get method 

        [HttpPost]
        public IActionResult DeleteTrainerSchedule(TrainerSchedule trainerSchedule)
        {
            iTrainerScheduleRepo.DeleteTrainerScheduleAsync(trainerSchedule).Wait();

            return RedirectToAction("SearchTrainers");
        }// end of delete trainer schedule post method



        public async Task AddTrainerHelper(Trainer trainer)
        {
            await iTrainerScheduleRepo.AddTrainerAsync(trainer);
        }// end of helper method

        public async Task AddTrainerScheduleHelper(TrainerSchedule trainerSchedule)
        {
            await iTrainerScheduleRepo.AddTrainerScheduleAsync(trainerSchedule);
        }// end of helper method


    }
}

TrainingApp/Areas/Trainers/Controllers/TrainersController.cs
using TrainingApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrainingApp.Models;
using TrainingApp.DataAccess.Repository.IRepository;

namespace TrainingApp.Areas.Trainers.Controllers
{
    public class TrainersController : Controller
    {

        private ITrainerRepo iTrainerRepo;

        public TrainersController(ITrainerRepo repo)
        {
            iTrainerRepo = repo;
        }

        public IActionResult ListAllAvailableTrainers()
        {
            List<Trainer> trainerList = ListAllAvailableTrainersHelper();

            return View("~/Views/Trainers/ListAllAvailableTrainers.cshtml", trainerList);
        }

        public List<Trainer> ListAllAvailableTrainersHelper()
        {
            List<Trainer> trainersList = iTrainerRepo.ListAllAvailableTrainers();

            return trainersList;
        }
    }
}

TrainingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrainingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               data-toggle="dropdown">
                                Trainers
                            </a>
                            <div class="dropdown-menu">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trainers" asp-action="ListAllAvailableTrainers">All Trainers</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TrainerSchedule" asp-action="SearchTrainers">Search Trainers</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="TrainerSchedule" asp-action="AddTrainers">Add Trainers</a>
                            </div>
                        </li>
                           @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                User & Role Management
                                    </a>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="AssignAppUsers">Assign User Roles</a>
                                </div>
                                </li>
                            }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TrainingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>