TrainingApp/Areas/Trainers/Controllers/TrainerScheduleController.cs
using TrainingApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using System.Security.Claims;
using TrainingApp.DataAccess.Repository.IRepository;
using TrainingApp.Models;

namespace TrainingApp.Areas.Trainers.Controllers
{
    public class TrainerScheduleController : Controller
    {
        private ITrainerRepo iTrainerRepo;
        private ITrainerScheduleRepo iTrainerScheduleRepo;
        private IApplicationUserRepo iApplicationUserRepo;
        private ITrainingSessionRepo iTrainingSessionRepo;


        public TrainerScheduleController(ITrainerRepo repo, ITrainerScheduleRepo trainerScheduleRepo, IApplicationUserRepo applicationUserRepo, ITrainingSessionRepo trainingSessionRepo)
        {
            iTrainerRepo = repo;
            iTrainerScheduleRepo = trainerScheduleRepo;
            iApplicationUserRepo = applicationUserRepo;
            iTrainingSessionRepo = trainingSessionRepo;
        }

        public void PopulateDropDownList()
        {
            ViewData["TrainerList"] = new SelectList(iTrainerRepo.ListAllAvailableTrainers(), "trainerId", "UserName");
        }

        [HttpGet]
        public IActionResult SearchTrainers()
        {
            PopulateDropDownList();

            SearchTrainersViewModel trainerViewModel = new SearchTrainersViewModel();

            return View(trainerViewModel);
        }

        [HttpPost]
        public IActionResult SearchTrainers(SearchTrainersViewModel trainerViewModel)
        {
            PopulateDropDownList();

            trainerViewModel.trainerScheduleList = SearchTrainersHelper(trainerViewModel);

            return View(trainerViewModel);
        }

        public List<TrainerSchedule> SearchTrainersHelper(SearchTrainersViewModel trainerViewModel)
        {
            List<TrainerSchedule> trainersSchedulesList = iTrainerScheduleRepo.ListOfTrainerSchedules();

            if (trainerViewModel.SportType != null)
            {
                trainersSchedulesList = trainersSchedulesList.Where(t => t.trainer.sportType == trainerViewModel.SportType).ToList();


            }

            return trainersSchedulesList;

        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AddTrainers()
        {
            PopulateDropDownList();

            return View("~/Views/TrainerSchedule/AddTrainers.cshtml");
        }

        [HttpPost]
        public IActionResult AddTrainers(AddTrainersViewModel trainerViewModel)
        {
            if (ModelState.IsValid)
            {
                //1. Add a Trainer
                Trainer trainer = new Trainer(trainerViewModel.firstName, trainerViewModel.lastName, trainerViewModel.sportType, trainerViewModel.email, trainerViewModel.phoneNumber, trainerViewModel.passWord);
                AddTrainerHelper(trainer).Wait();

                //2. Add Trainer Schedule
                string trainerId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                TrainerSchedule trainerSchedule = new TrainerSchedule(trainerViewModel.StartDateTime, trainerViewModel.EndDateTime, trainerId);
                AddTrainerScheduleHelper(trainerSchedule).Wait();

                return RedirectToAction("SearchTrainers");
            }// end of is valid true
            else
            {
                PopulateDropDownList();
                return View("~/Views/TrainerSchedule/AddTrainers.cshtml"); // returns them back to page if they dont provide the correct infomoration
            }// end of is valid false
        }// end of addtrainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditTrainer(string TrainerID)
        {

            Trainer trainer = iTrainerRepo.FindTrainer(TrainerID);

            return View("~/Views/TrainerSchedule/EditTrainers.cshtml", trainer);
        }//end of edit trainer post method

        [HttpPost]
        public IActionResult EditTrainer(Trainer trainer)
        {

            iTrainerRepo.EditTrainerAsync(trainer).Wait();

            return RedirectToAction("SearchTrainers");

        } //end of edit trainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult ConfirmDeleteTrainers(string TrainerID)
        {

            Trainer trainer = iTrainerRepo.FindTrainer(TrainerID);

            return View("~/Views/TrainerSchedule/ConfirmDeleteTrainers.cshtml", trainer);
        }//end of delete trainer get method

        [HttpPost]
        public IActionResult DeleteTrainer(Trainer trainer)
        {

            iTrainerRepo.DeleteTrainerAsync(trainer).Wait();

            return RedirectToAction("SearchTrainers");
        }//end of delete trainer post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditTrainerSchedule(int TrainerScheduleID)
        {

            TrainerSchedule trainerSchedule = iTrainerScheduleRepo.FindTrainerSchedule(TrainerScheduleID);

            return View("~/Views/TrainerSchedule/EditTrainerSchedule.cshtml", trainerSchedule);
        } // end of edit trainer schedule get method

        [HttpPost]
        public IActionResult EditTrainerSchedule(TrainerSchedule trainerSchedule)
        {

            iTrainerScheduleRepo.EditTrainerScheduleAsync(trainerSchedule).Wait();

            return RedirectToAction("SearchTrainers");

        } // end of edit trainer schedule post method

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult ConfirmDeleteTrainersSchedule(int TrainerScheduleID)
        {

            TrainerSchedule trainerSchedule = iTrainerScheduleRepo.FindTrainerSchedule(TrainerScheduleID);

            return View("~/Views/TrainerSchedule/EditTrainerSchedule.cshtml", trainerSchedule);
        }// end of confirm delete trainer schedule get method 

        [HttpPost]
        public IActionResult DeleteTrainerSchedule(TrainerSchedule trainerSchedule)
        {
            iTrainerScheduleRepo.DeleteTrainerScheduleAsync(trainerSchedule).Wait();

            return RedirectToAction("SearchTrainers");
        }// end of delete trainer schedule post method



        public async Task AddTrainerHelper(Trainer trainer)
        {
            await iTrainerScheduleRepo.AddTrainerAsync(trainer);
        }// end of helper method

        public async Task AddTrainerScheduleHelper(TrainerSchedule trainerSchedule)
        {
            await iTrainerScheduleRepo.AddTrainerScheduleAsync(trainerSchedule);
        }// end of helper method


    }
}

TrainingApp/Areas/Trainers/Controllers/TrainingSessionController.cs
using TrainingApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using TrainingApp.DataAccess.Repository.IRepository;
using TrainingApp.Models;

namespace TrainingApp.Areas.Trainers.Controllers
{
    public class TrainingSessionController : Controller
    {
        private ITrainerRepo iTrainerRepo;
        private ITrainerScheduleRepo iTrainerScheduleRepo;
        private IApplicationUserRepo iApplicationUserRepo;
        private ITrainingSessionRepo iTrainingSessionRepo;


        public TrainingSessionController(ITrainerRepo repo, ITrainerScheduleRepo trainerScheduleRepo, IApplicationUserRepo applicationUserRepo, ITrainingSessionRepo trainingSessionRepo)
        {
            iTrainerRepo = repo;
            iTrainerScheduleRepo = trainerScheduleRepo;
            iApplicationUserRepo = applicationUserRepo;
            iTrainingSessionRepo = trainingSessionRepo;
        }

        [Authorize(Roles = "Athlete")]
        public IActionResult BookTrainingSession(int trainerScheduleID)
        {
            ViewData["ErrorMessage"] = "None";

            TrainerSchedule trainerSchedule =
                iTrainerScheduleRepo.FindTrainerSchedule(trainerScheduleID);

            if (!trainerSchedule.isAvailable)
            {

                ViewData["ErrorMessage"] = "Training session requested not available Between" +
                    trainerSchedule.trainerScheduleStartDateTime.ToString() + " "
                    + trainerSchedule.trainerScheduleEndDateTime.ToString();
                return View();

            }
            else
            {
                string trainerID = trainerSchedule.trainerId;
                DateTime startSessionTime = trainerSchedule.trainerScheduleStartDateTime;
                DateTime endSessionTime = trainerSchedule.trainerScheduleEndDateTime;
                string athleteID = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                TrainingSession trainingSession = new TrainingSession(startSessionTime,
                    endSessionTime, athleteID, trainerID);

                iTrainingSessionRepo.BookTrainingSessionAsync(trainingSession).Wait();

                trainerSchedule.isAvailable = false;
                iTrainerScheduleRepo.EditTrainerScheduleAsync(trainerSchedule).Wait();

                List<TrainingSession> ListOfTrainingSessions = iTrainingSessionRepo.TraniningSessionList();

                return View("ListOfTrainingSessions", ListOfTrainingSessions);




            }

        }

        //public bool BookTrainingSessionHelper(string athleteID, DateTime requestedTrainingSessionStartDate, DateTime requestedTrainingSessionEndDate)
        //{

        //    bool bookedSession;

        //    // 1. Finds athletes trainer

        //    Trainer trainer = iApplicationUserRepo.FindTrainerForAthlete(athleteID); //use application user

        //    // 2. Checks trainers availability at requested date/time

        //    TrainerSchedule trainerAvailability = iTrainingSessionRepo.CheckTrainerAvailability(trainer.Id, requestedTrainingSessionStartDate,requestedTrainingSessionEndDate);

        //    if (trainerAvailability != null)
        //    {

        //        trainerAvailability.trainerId = athleteID;
        //        trainerAvailability.isAvailable = false;

        //        //3a. If available, book session

        //        iTrainingSessionRepo.BookTrainingSessionAsync(trainerAvailability).Wait();
        //        bookedSession = true;

        //    }
        //    else
        //    {
        //        //3b. If not available, session not made
        //        bookedSession = false;

        //    }

        //    return bookedSession;

        //}

        //public IActionResult BookTrainingSession(int trainerScheduleID)
        //{
        //    /*


        //    string trainerID = trainerSchedule.trainerId;            
        //    DateTime startSessionTime = trainerSchedule.trainerScheduleStartDateTime;
        //    DateTime endSessionTime = trainerSchedule.trainerScheduleEndDateTime;
        //    string athleteID = from login;

        //    TrainingSession trainingSession =
        //        new TrainingSession(startSessionTime, endSessionTime, athleteID,
        //        trainerID);
        //    database.TrainingSessions.Add(trainingSession);
        //    */
        //    //make the trainer unavailable for this time.


        //    return View();//Confirm Training Session appointment to Athlete
        //}
    }
}

TrainingApp/Areas/Trainers/Views/TrainerSchedule/AddTrainers.cshtml
@using TrainingApp.ViewModel
@model AddTrainersViewModel
@{
    ViewData["Title"] = "Add Trainers";
}

<h1>Add Trainers</h1>

<div asp-validation-summary="All" class="text-danger"></div>
@{ 
    // Warning label
}

<form asp-controller="TrainerSchedule" asp-action="AddTrainers" method="post">
    <div class="form-group">
        <label>First Name:</label>
        <input asp-for="firstName" class="form-control" />
    </div>

    <div class="form-group">
        <label>Last Name:</label>
        <input asp-for="lastName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sports Type:</label>
        <select asp-for="sportType" class="form-control">
            <option value="null">None</option>
            <option value="Basketball">Basketball</option>
            <option value="Soccer">Soccer</option>
            <option value="Football">Football</option>
        </select>
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input asp-for="email" class="form-control" />
    </div>
    <div class="form-group">
        <label>Phone Number:</label>
        <input asp-for="phoneNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label>Password:</label>
        <input asp-for="passWord" class="form-control" />
    </div>
    <div class="form-group">
        <label>Schedule Start Date and Time</label>
        <input asp-for="StartDateTime" class="form-control" />

    </div>
    <div class="form-group">
        <label>Schedule End Date and Time</label>
        <input asp-for="EndDateTime" class="form-control" />

    </div>

    <button type="submit" class="btn-primary">Add Trainer</button>
</form>

TrainingApp/Areas/Trainers/Views/TrainerSchedule/BookTrainingSession.cshtml
@*@model TrainingSession
@{ ViewData["Title"] = "Book Training Session"; }

<h4>Book Training Session</h4>

<form asp-controller="TrainerSchedule" asp-action="BookTrainingSession" method="post">

    <div class="form-group">

        <label>Training Session Date Time</label>

        <input asp-for="trainingSessionDate" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Book Training Session</button>

    @if (ViewBag.ErrorMessage != "None")
    {
        <p>@ViewBag.ErrorMessage</p>
    }

</form>*@ 

TrainingApp/Areas/Trainers/Views/TrainerSchedule/ConfrimDeleteTrainers.cshtml
@using TrainingApp.Models
@model Trainer
@{
    ViewData["Title"] = "Confirm Delete Trainers ";
}

<h1>Confirm Delete Trainers</h1>

<div asp-validation-summary="All" class="text-danger"></div>
@{ 
    // Warning Label
}

<form asp-controller="TrainerSchedule" asp-action="DeleteTrainer" method="post">

    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        <label>First Name:</label>
        <input readonly asp-for="firstName" class="form-control" />
    </div>

    <div class="form-group">
        <label>Last Name:</label>
        <input readonly asp-for="lastName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sports Type:</label>
        <input readonly asp-for="sportType" class="form-control" />
    </div>

    <button type="submit" class="btn-primary">Delete Trainer</button>
</form>

TrainingApp/Areas/Trainers/Views/TrainerSchedule/ConfrimDeleteTrainersSchedule.cshtml
@using TrainingApp.Models
@model TrainerSchedule
@{
    ViewData["Title"] = "Confirm Delete Trainers Schedule";
}

<h1>Confirm Delete Trainers Schedule</h1>

<div asp-validation-summary="All" class="text-danger"></div>
@{ 
    // Warning Label
}

<form asp-controller="TrainerSchedule" asp-action="DeleteTrainersSchedule" method="post">

    @Html.HiddenFor(m => m.trainerId)

    <div class="form-group">
        <label>Trainer:</label>
        <input readonly asp-for="trainerId" class="form-control" />
    </div>
    <div class="form-group">
        <label>Schedule Start Date and Time</label>
        <input readonly asp-for="trainerScheduleStartDateTime" class="form-control" />

    </div>
    <div class="form-group">
        <label>Schedule End Date and Time</label>
        <input readonly asp-for="trainerScheduleEndDateTime" class="form-control" />

    </div>

    <button type="submit" class="btn-primary">Delete Trainer</button>
</form>

TrainingApp/Areas/Trainers/Views/TrainerSchedule/EditTrainers.cshtml
@using TrainingApp.Models
@model Trainer
@{
    ViewData["Title"] = "Edit Trainers";
}

<h1>Edit Trainers</h1>

<div asp-validation-summary="All" class="text-danger"></div>
@{ 
    // Warning Label
}

<form asp-controller="TrainerSchedule" asp-action="EditTrainers" method="post">

    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        <label>First Name:</label>
        <input asp-for="firstName" class="form-control" />
    </div>

    <div class="form-group">
        <label>Last Name:</label>
        <input asp-for="lastName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sports Type:</label>
        <select asp-for="sportType" class="form-control">
            <option value="null">None</option>
            <option value="Basketball">Basketball</option>
            <option value="Soccer">Soccer</option>
            <option value="Football">Football</option>
        </select>
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label>Phone Number:</label>
        <input asp-for="PhoneNumber" class="form-control" />
    </div>
    <button type="submit" class="btn-primary">Edit Trainer</button>
</form>

TrainingApp/Areas/Trainers/Views/TrainerSchedule/EditTrainersSchedule.cshtml
@using TrainingApp.Models
@model TrainerSchedule
@{
    ViewData["Title"] = "Edit Trainer Schedule";
}

<h1>Edit Trainer Schedule</h1>

<div asp-validation-summary="All" class="text-danger"></div>
@{ 
    // Warning label
}

<form asp-controller="TrainerSchedule" asp-action="EditTrainerSchedule" method="post">

    @Html.HiddenFor(m => m.trainerId)

    <div class="form-group">
        <label>Trainer:</label>
        <input asp-for="trainerId" class="form-control" />
    </div>
    <div class="form-group">
        <label>Schedule Start Date and Time</label>
        <input asp-for="trainerScheduleStartDateTime" class="form-control" />

    </div>
    <div class="form-group">
        <label>Schedule End Date and Time</label>
        <input asp-for="trainerScheduleEndDateTime" class="form-control" />

    </div>


    <button type="submit" class="btn-primary">Edit Trainer</button>
</form>

TrainingApp/Areas/Trainers/Views/TrainerSchedule/SearchTrainers.cshtml
@using TrainingApp.Models
@using TrainingApp.ViewModel
@model SearchTrainersViewModel
@{
    ViewData["Title"] = "Search Trainers";
}

<h1>Search Trainers</h1>

<form asp-controller="TrainerSchedule" asp-action="SearchTrainers" method="post">
    <div class="form-group">
        <label>Sports Type</label>
        <select asp-for="SportType" class="form-control">
            <option value="">None</option>
            <option value="Basketball">Basketball</option>
            <option value="Soccer">Soccer</option>
            <option value="Football">Football</option>

        </select>
    </div>

    <div class="form-group">
        <label>Start Date & Time</label>
        <input asp-for="StartDateTime" class="form-control"/>
    </div>

    <div>
        <label>End Date & Time</label>
        <input  asp-for="EndDateTime" class="form-control"/>
    </div>

    <button type="submit" class="btn-primary">Search</button>

</form>
@if (Model.trainerScheduleList != null)
{
    <table class="table table-bordered table-striped">

        <thead>
            <tr>
                <th>Trainer</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th> Schedule Start Date and Time </th>
                <th> Schedule End Date and Time </th>
                <th>Available</th>
                @if (User.IsInRole("Admin"))
                {
                    <th>Choose Trainer to Modify</th>
                    <th>Choose Trainer Schedule to Modify</th>
                    <th>Choose Trainer to Remove</th>
                    <th>Choose Trainer Schedule to Remove</th>


                }
                @if (User.IsInRole("Athlete"))
                {
                    <th>Book Training Session</th>
                }

            </tr>
        </thead>
        <tbody>

            @foreach (TrainerSchedule eachTrainerSchedule in Model.trainerScheduleList)
            {
            <tr>
                <td>
                    @eachTrainerSchedule.trainer.fullName
                </td>
                <td>@eachTrainerSchedule.trainer.Email</td>
                <td>@eachTrainerSchedule.trainer.PhoneNumber</td>
                <td>@eachTrainerSchedule.trainerScheduleStartDateTime</td>
                <td>@eachTrainerSchedule.trainerScheduleEndDateTime</td>
                
                <td>@eachTrainerSchedule.isAvailable</td>

                @if (User.Identity.IsAuthenticated)
                {

                    if (User.IsInRole("Admin"))
                    {
                        <td>

                            <a class="btn-btn-primary" asp-controller="TrainerSchedule" asp-action="EditTrainer" asp-route-trainerID="@eachTrainerSchedule.trainerId">Edit Trainer</a>

                        </td>

                        <td>

                            <a class="btn-btn-primary" asp-controller="TrainerSchedule" asp-action="EditTrainerSchedule" asp-route-TrainerScheduleID="@eachTrainerSchedule.trainerScheduleID">Edit Trainer Schedule</a>

                        </td>

                        <td>

                            <a class="btn-btn-primary" asp-controller="TrainerSchedule" asp-action="ConfirmDeleteTrainers" asp-route-trainerID="@eachTrainerSchedule.trainerId">Delete Trainer</a>

                        </td>

                        <td>

                            <a class="btn-btn-primary" asp-controller="TrainerSchedule" asp-action="ConfirmDeleteTrainersSchedule" asp-route-TrainerScheduleID="@eachTrainerSchedule.trainerScheduleID">Delete Trainer Schedule</a>

                        </td>
                    }
                    if (User.IsInRole("Athlete"))
                    {
                        <td>

                            <a class="btn-btn-primary" asp-controller="TrainingSession" asp-action="BookTrainingSession" asp-route-trainerScheduleID="@eachTrainerSchedule.trainerScheduleID">Book Training Session</a>

                        </td>
                    }

                }

            </tr>
            }

        </tbody>
    </table>
}